{
 "title": "SVS",
 "time": { "from": "2019-10-26T03:53:22.000Z", "to": "2020-12-16T20:06:17.000Z" },
 "panels": [
  {
   "title": "Water Input",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  avg(\"Rainfall\") AS \"Rainfall\",\n  avg(\"Irrigation\") AS \"Irrigation\"\nFROM update_profile\nWHERE\n  $__timeFilter(\"Date\")\nGROUP BY 1, \"Crop\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Water profile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  avg(\"Nitrogen_1:Irrigation_1\") AS \"\"\"Nitrogen_1:Irrigation_1\"\"\",\n  avg(\"Nitrogen_1:Irrigation_2\") AS \"\"\"Nitrogen_1:Irrigation_2\"\"\",\n  avg(\"Nitrogen_2:Irrigation_1\") AS \"\"\"Nitrogen_2:Irrigation_1\"\"\",\n  avg(\"Nitrogen_2:Irrigation_2\") AS \"\"\"Nitrogen_2:Irrigation_2\"\"\",\n  avg(\"Nitrogen_3:Irrigation_1\") AS \"\"\"Nitrogen_3:Irrigation_1\"\"\",\n  avg(\"Nitrogen_3:Irrigation_2\") AS \"\"\"Nitrogen_3:Irrigation_2\"\"\",\n  avg(\"Nitrogen_4:Irrigation_1\") AS \"\"\"Nitrogen_4:Irrigation_1\"\"\",\n  avg(\"Nitrogen_4:Irrigation_2\") AS \"\"\"Nitrogen_4:Irrigation_2\"\"\"\nFROM update_profile\nGROUP BY 1, \"Crop\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Soil Moisture Deficit Profile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  avg(\"deficitNitrogen_1:Irrigation_1\") AS \"\"\"Nitrogen_1:Irrigation_1\"\"\",\n  avg(\"deficitNitrogen_1:Irrigation_2\") AS \"\"\"Nitrogen_1:Irrigation_2\"\"\",\n  avg(\"deficitNitrogen_2:Irrigation_1\") AS \"\"\"Nitrogen_2:Irrigation_1\"\"\",\n  avg(\"deficitNitrogen_2:Irrigation_2\") AS \"\"\"Nitrogen_2:Irrigation_2\"\"\",\n  avg(\"deficitNitrogen_3:Irrigation_1\") AS \"\"\"Nitrogen_3:Irrigation_1\"\"\",\n  avg(\"deficitNitrogen_3:Irrigation_2\") AS \"\"\"Nitrogen_3:Irrigation_2\"\"\",\n  avg(\"deficitNitrogen_4:Irrigation_1\") AS \"\"\"Nitrogen_4:Irrigation_1\"\"\",\n  avg(\"deficitNitrogen_4:Irrigation_2\") AS \"\"\"Nitrogen_4:Irrigation_2\"\"\"\nFROM update_profile\nGROUP BY 1, \"Crop\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Water Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  avg(\"Drainage\") AS \"Drainage\",\n  avg(\"AET\") AS \"AET\",\n  avg(\"PET\") AS \"PET\"\nFROM update_waterbalance\nWHERE\n  $__timeFilter(\"Date\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}