{
 "title": "Canopy and Soil Water Balance",
 "time": { "from": "2019-07-31T01:19:38.196Z", "to": "2022-03-13T03:35:34.691Z" },
 "panels": [
  {
   "title": "Mean scaled NDVI measurements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Date\",$__interval),\n  avg(mean) AS \"mean\"\nFROM update_canopy\nGROUP BY 1, \"Irrigation\", \"Nitrogen\", \"Var2\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 60 cm SWB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"Wt_Nitrogen 1\" AS \"WaterBalance N1\",\n  \"Wt_Nitrogen 2\" AS \"WaterBalance N2\",\n  \"Wt_Nitrogen 3\" AS \"WaterBalance N3\",\n  \"Wt_Nitrogen 4\" AS \"WaterBalance N4\",\n  \"Nitrogen 1\" AS \"Measurement N1\",\n  \"Nitrogen 2\" AS \"Measurement N2\",\n  \"Nitrogen 3\" AS \"Measurement N3\",\n  \"Nitrogen 4\" AS \"Measurement N4\"\nFROM \"update_WaterBalance.1_60cm\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 60 cm SWB Drainage Prediction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"PET\",\n  \"Precipitation\",\n  \"Drainage_Nitrogen 1\" AS \"Nitrogen 1\",\n  \"Drainage_Nitrogen 2\" AS \"Nitrogen 2\",\n  \"Drainage_Nitrogen 3\" AS \"Nitrogen 3\",\n  \"Drainage_Nitrogen 4\" AS \"Nitrogen 4\"\nFROM \"update_WaterBalance.1_60cm\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 60 cm SWB with reseting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"Wt_Nitrogen 1\" AS \"WaterBalance N1\",\n  \"Wt_Nitrogen 2\" AS \"WaterBalance N2\",\n  \"Wt_Nitrogen 3\" AS \"WaterBalance N3\",\n  \"Wt_Nitrogen 4\" AS \"WaterBalance N4\",\n  \"SWD_Nitrogen 1\" AS \"Measurement N1\",\n  \"SWD_Nitrogen 2\" AS \"Measurement N2\",\n  \"SWD_Nitrogen 3\" AS \"Measurement N3\",\n  \"SWD_Nitrogen 4\" AS \"Measurement N4\"\nFROM \"update_WaterBalance.1_60cm_reset\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 60 cm SWB Drainage Prediction with Reseting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"PET\",\n  \"Precipitation\",\n  \"Drainage_Nitrogen 1\" AS \"Nitrogen 1\",\n  \"Drainage_Nitrogen 2\" AS \"Nitrogen 2\",\n  \"Drainage_Nitrogen 3\" AS \"Nitrogen 3\",\n  \"Drainage_Nitrogen 4\" AS \"Nitrogen 4\"\nFROM \"update_WaterBalance.1_60cm_reset_PETcor\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 60cm SWB with reseting and PET correction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"Wt_Nitrogen 1\" AS \"WaterBalance N1\",\n  \"Wt_Nitrogen 2\" AS \"WaterBalance N2\",\n  \"Wt_Nitrogen 3\" AS \"WaterBalance N3\",\n  \"Wt_Nitrogen 4\" AS \"WaterBalance N4\",\n  \"SWD_Nitrogen 1\" AS \"Measurement N1\",\n  \"SWD_Nitrogen 2\" AS \"Measurement N2\",\n  \"SWD_Nitrogen 3\" AS \"Measurement N3\",\n  \"SWD_Nitrogen 4\" AS \"Measurement N4\"\nFROM \"update_WaterBalance.1_60cm_reset_PETcor\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 60 cm SWB Drainage Prediction with Reseting and PET correction by NDVI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Date\" AS \"time\",\n  \"PET\",\n  \"Precipitation\",\n  \"Drainage_Nitrogen 1\" AS \"Nitrogen 1\",\n  \"Drainage_Nitrogen 2\" AS \"Nitrogen 2\",\n  \"Drainage_Nitrogen 3\" AS \"Nitrogen 3\",\n  \"Drainage_Nitrogen 4\" AS \"Nitrogen 4\"\nFROM \"update_WaterBalance.1_60cm_reset\"\nORDER BY 1"
    }
   ]
  }
 ]
}