version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: svs_grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - ./data:/var/lib/grafana
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
